apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
{{ include "airflow.labels" . | indent 4 }}
  annotations:
  {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | trim | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: airflow
    app.kubernetes.io/name: {{ include "airflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort | default 8080 }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort.http))) }}
      nodePort: {{ .Values.service.nodePort.http }}
      {{- end }}
      targetPort: 8080
