apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airflow.fullname" . }}-sql-proxy-env
  labels:
{{ include "airflow.labels" . | indent 4 }}
data:
  POSTGRES_HOST: {{ include "airflow.fullname" . }}-sql-proxy
  POSTGRES_PORT: {{ .Values.cloudsql.service.externalPort | quote }}
  POSTGRES_DB: {{ required "A valid .Values.cloudsql.database entry is required!" .Values.cloudsql.database }}
