{{- if and .Values.cloudsql.enabled (eq .Values.postgresql.enabled false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-sql-proxy
  labels:
{{ include "airflow.labels" . | indent 4 }}
type: Opaque
data:
  credentials.json: |-
    {{ required "A valid .Values.cloudsql.serviceAccountKey entry required!" .Values.cloudsql.serviceAccountKey }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-sql-proxy-env
  labels:
{{ include "airflow.labels" . | indent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ required "A valid .Values.cloudsql.password entry required!" .Values.cloudsql.password | b64enc }}
  POSTGRES_USER: {{ required "A vlid .Values.cloudsql.user entry required!" .Values.cloudsql.user | b64enc }}
{{- end -}}
