apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-gcs-syncd
  labels:
{{ include "airflow.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "airflow.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "airflow.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.sync.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag }}"
          imagePullPolicy: {{ .Values.sync.image.pullPolicy }}
          command:
          - /bin/bash
          - /sync.sh
          args:
          - {{ .Values.sync.bucket }}
          - /dags
          volumeMounts:
          - name: dags
            mountPath: dags
          resources:
            {{- toYaml .Values.sync.resources | trim | nindent 12 }}
      # Location of this Pod must be on the same node as the airflow Pod
      # The Pod is affined to the airflow Pod.
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "airflow.name" . }}
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: kubernetes.io/hostname
    {{- with .Values.sync.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: dags
        persistentVolumeClaim:
          claimName: {{ include "airflow.fullname" . }}-dags
    
