{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "airflow.labels" . | indent 4 }}
  name: {{ include  "airflow.serviceAccountName" . }}
{{- end -}}
